version: '3.4'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '5001:5000'
    networks:
      - appnetwork
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app
      - FLASK_ENV=development
      - EMAIL_ADDRESS=ceneowebscrapper@gmail.com
      # DELETE PASSWORD BEFORE COMMITING!
      - EMAIL_PASSWORD=#####
      - DATABASE_URI=postgresql://hello:hello@db:5432/hello_db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello_db
    networks:
      - appnetwork

volumes:
  postgres_data:


networks:
  appnetwork:
    driver: bridge
