version: '3.4'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '5001:5000'
    networks:
      - appnetwork
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app
      - FLASK_ENV=development
      - EMAIL_ADDRESS=ceneowebscrapper@gmail.com
      - EMAIL_PASSWORD=populate_the_password_here
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello_db

volumes:
  postgres_data:

networks:
  appnetwork:
    driver: bridge
