version: '3.4'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
    ports:
      - '5001:5000'
    env_file:
      - ./.env.dev
    networks:
      - appnetwork
    depends_on:
      - db
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app
      - FLASK_ENV=development
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello12
      - POSTGRES_DB=hello_db
    networks:
      - appnetwork
      
volumes:
  postgres_data:

networks:
  appnetwork:
    driver: bridge

